default: &default
  host: localhost
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password:
  timeout: 5000

development:
  <<: *default
  database: newsbot_development

test:
  <<: *default
  database: newsbot_test
